export const countryList = [
  "Russia",
  "Germany",
  "U.K.",
  "France",
  "Italy ",
  "Spain ",
  "Ukraine ",
  "Poland ",
  " Romania",
  " Netherlands",
  "Belgium ",
  " Greece",
  "Czech Republic ",
  "Portugal ",
  "Sweden ",
  "Hungary ",
  " Belarus",
  " Austria",
  " Serbia",
  "Switzerland ",
  " Bulgaria",
  "Denmark ",
  " Finland",
  " Slovakia",
  " Norway",
  " Ireland",
  "Croatia ",
  "Moldova ",
  "Bosnia &amp; Herzegovina ",
  "Albania ",
  "Lithuania ",
  " TFYR Macedonia",
  " Slovenia",
  "Latvia ",
  "Estonia ",
  " Montenegro",
  "Luxenbourg ",
  "Malta ",
  "Iceland ",
  "Andora ",
  "Monaco ",
  "Liechtenstein/li&gt; ",
  " San Marino",
  "Holy See ",
];

export const phoneCodes = ["+11", "+22", "+33", "+44", "+55", "+66"];
